version: "3"
services:
  app:
    build: .
    command: /opt/inventory-app/start.sh
    environment:
      DB_CKAN_HOST: db
      DB_CKAN_USER: ckan
      DB_CKAN_PASSWORD: pass
      DB_CKAN_DB: ckan
    depends_on:
      - db
      - solr
    ports:
      - "5000:5000"
    volumes:
      - ckan:/usr/lib/ckan
      - ./config:/etc/ckan
      - .:/opt/inventory-app
      
  db:
    image: datagov/catalog-db:latest
    environment:
      POSTGRES_USER: postgres
      DB_CKAN_USER: ckan
      DB_CKAN_PASSWORD: pass
      DB_CKAN_DB: ckan

  solr:
    image: datagov/catalog-solr:inventory

volumes:
  ckan:
