version: "3.7"
services:
  ckan:
    image: datagov/ckanext-dcat_usmetadata:${CKAN_VERSION}
    build:
      context: .
      args:
        CKAN_VERSION: ${CKAN_VERSION}
    env_file:
      - .env
    environment:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@db/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@db/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@db/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1
      CKAN_DATAPUSHER_URL: http://localhost:8080/  # datapusher is not really enabled
      CKAN__PLUGINS: dcat_usmetadata usmetadata
      PYTHONDONTWRITEBYTECODE: 1
    # command: /bin/bash -c "while ! nc -zv db 5432; do echo \"CKAN** Waiting for DB\"; sleep 3; done; /srv/app/start_ckan_development.sh"
    depends_on:
      - db
      - solr
      - redis
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - .:/srv/app/src_extensions/ckanext-dcat_usmetadata
      
  db:
    image: ckan/ckan-postgres-dev:${CKAN_VERSION}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "pg_isready -u ckan"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
  solr:
    image: datagov/catalog.data.gov.solr:latest
    ports:
      - "8983:8983"

volumes:
  pg_data:
