version: "3.2"
services:
  app:
    build: .
    command: /opt/inventory-app/start.sh
    env_file:
      - .env
    links:
      - db
      - solr
      - redis
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ckan:/usr/lib/ckan
      - ./config:/etc/ckan
      - .:/opt/inventory-app
      - ckan_storage:/var/lib/ckan
      - .:/srv/app/src_extensions/dcat_usmetadata
  db:
    image: ckan/postgresql
    expose:
      - "5432"
  solr:
    image: datagov/catalog-solr:inventory
  redis:
    image: redis:alpine

volumes:
  ckan_storage:
  ckan:
  pg_data:
  solr_data:
