version: "3.7"
services:
  cypress:
    image: cypress/included:7.7.0
    environment:
      NODE_ENV: test
    entrypoint: []
    command: /bin/bash -c 'npx wait-on http://ckan:5000/api/action/status_show && npx cypress install && npx cypress run'
    # Run a specific test
    # command: /bin/bash -c 'npx wait-on http://ckan:5000/api/action/status_show && npx cypress install && npx cypress run --spec cypress/integration/additional-metadata.spec.js'
    ipc: host
    working_dir: /e2e
    depends_on:
      - ckan
    volumes:
      - .:/e2e

  ckan:
    ipc: host
  db:
    ipc: host
  redis:
    ipc: host
  solr:
    ipc: host
