version: 2

jobs:
  build_gsa_ckan_inventory:
    working_directory: ~
    machine: true
    steps:
      - run: echo "Github requires this job for CI"
  test_local_docker:
    working_directory: ~/ckanext-dcat_usmetadata
    machine: true
    steps:
      - checkout
#      - run: make lint-all
      - run:
          name: Start CKAN
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.seed.yml up -d
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait http://localhost:5000/dataset -timeout 120s
      # TODO fix this:
      # - run:
      #     name: Run ckanext-dcat_usmetadata Tests
      #     command: |
      #       docker-compose exec app /bin/bash -c "source /usr/lib/ckan/bin/activate && nosetests --ckan --with-pylons=src_extensions/dcat_usmetadata/docker_test.ini src_extensions/dcat_usmetadata/"
      - run:
          name: Upgrade Node to 12
          command: |
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            nvm install v12.14.1
            nvm alias default v12.14.1
            nvm install v12
            node -v
            nvm alias default v12
      - run:
          name: Prepare latest build files
          command: npm i -g yarn && yarn build
      - run:
          name: Install and run cypress
          command: |
            yarn && npx cypress run


workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gsa_ckan_inventory
      - test_local_docker
