version: 2
jobs:
  test_local_docker:
    working_directory: ~/ckanext-dcat_usmetadata
    machine: true
    steps:
      - checkout
      - run:
          name: Start CKAN
          command: |
            docker-compose build
            docker-compose up -d
      - run: 
          name: Lint 
          command: make lint
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait http://localhost:5000/dataset -timeout 120s
      - run:
          name: Run ckanext-dcat_usmetadata Tests
          command: make test
      - run:
          name: Install and run cypress
          command: |
            npm install && npx cypress run

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_local_docker
