version: 2

jobs:
  build_gsa_ckan_inventory:
    working_directory: ~
    machine: true
    steps:
      - run: echo "Github requires this job for CI"

  build_metadata_app:
    docker:
      - image: circleci/node:12.13.0
    working_directory: ~/ckanext-dcat_usmetadata
    steps:
      - checkout
      - run:
          name: Lint JavaScript
          command: make app-lint
      - run:
          name: Prepare latest build files
          command: CI=false yarn build
      - run:
          name: Run unit tests
          command: cd ~/ckanext-dcat_usmetadata/metadata-app/ && yarn test
      - persist_to_workspace:
          root: ~/
          paths:
            - "ckanext-dcat_usmetadata"

  test_local_docker:
    working_directory: ~/ckanext-dcat_usmetadata
    machine: true
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Start CKAN
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.seed.yml up -d
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait http://localhost:5000/dataset -timeout 120s
      - run:
          name: Lint python
          command: make lint-all
      # TODO fix this:
      # - run:
      #     name: Run ckanext-dcat_usmetadata Tests
      #     command: |
      #       docker-compose exec app /bin/bash -c "source /usr/lib/ckan/bin/activate && nosetests --ckan --with-pylons=src_extensions/dcat_usmetadata/docker_test.ini src_extensions/dcat_usmetadata/"
      - run:
          name: Install and run e2e tests using cypress
          command: |
            npm i && npx cypress run


workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gsa_ckan_inventory
      - build_metadata_app
      - test_local_docker:
          requires:
            - build_metadata_app
