version: 2
jobs:
  test_local_docker:
    working_directory: ~/ckanext-dcat_usmetadata
    machine: true
    steps:
      - checkout
      - run: make lint-all
      - run:
          name: Start CKAN
          command: |
            make build
            make up-with-data
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait http://localhost:5000/dataset -timeout 120s
      - run:
          name: Run ckanext-dcat_usmetadata Tests
          command: |
            docker-compose exec app /bin/bash -c "source $(CKAN_HOME)/bin/activate && nosetests --ckan --with-pylons=src_extensions/dcat_usmetadata/docker_test.ini src_extensions/dcat_usmetadata/"
      - run:
          name: Install and run cypress
          command: |
            npm install && npx cypress run

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_local_docker
      - build_gsa_ckan_inventory
