export default {
  dataQualityUSG: '',
  themes: '',
  describedBy: '',
  describedByType: '',
  accrualPeriodicity: '',
  landingPage: '',
  languageSubTag: 'en',
  languageRegSubTag: 'US',
  primaryITInvestmentUIIUSG: '',
  references: '',
  issued: '',
  systemOfRecordsUSG: '',
  isPartOf: '',
  isParent: 'No',
  parentDataset: '',
};
