export default {
  dataQuality: '',
  themes: '',
  describedByType: '',
  accrualPeriodicity: '',
  landingPage: '',
  languageSubTag: 'en',
  languageRegSubTag: 'US',
  primaryITInvestmentUIIUSG: '',
  references: '',
  issued: '',
  systemOfRecordsUSG: '',
  isPartOf: '',
  isParent: '',
  parentDataset: '',
};
