export default {
  dataQualityUSG: '',
  themes: '',
  describedBy: '',
  describedByType: '',
  accrualPeriodicity: '',
  landingPage: '',
  languageSubTag: '',
  languageRegSubTag: '',
  primaryITInvestmentUIIUSG: '',
  references: '',
  issued: '',
  systemOfRecordsUSG: '',
  isPartOf: '',
};
