export default {
  title: '',
  description: '',
  publisher: '',
  subagency: '',
  public_access_level: '',
  data_quality: '',
  license: '',
  license_others: '',
  identifier: '',
  rights: 'false',
  rights_desc: '',
  spatial: 'false',
  spatial_location: 'false',
  temporal: 'false',
  temporal_start_date: '',
  temporal_end_date: '',
  contact_name: '',
  contact_email: '',
  unique_id: '',
  url: '',
};
