export default {
  title: 'Title',
  contact_name: 'Contact Name',
  unique_id: 'Unique ID',
  contact_email: 'Contact Email',
  description: 'Description',
  publisher: 'Publisher',
  public_access_level: 'Public Access Level',
  data_quality: 'Access Level',
  rights_desc: 'Rights',
  spatial: 'Spatial',
  license: 'License',
  licenseOther: 'License',
  temporal: 'Temporal',
  tags: 'Tags',
  owner_org: 'Organization',
  temporal_start_date: 'Temporal Start Date',
  temporal_end_date: 'Temporal End Date',
};
