export default {
  title: 'Title',
  contact_name: 'Contact Name',
  unique_id: 'Unique ID',
  contact_email: 'Contact Email',
  description: 'Description',
  publisher: 'Publisher',
  public_access_level: 'Public Access Level',
  data_quality: 'Access Level',
  access_level_comment: 'Rights',
  spatial: 'Spatial',
  license_new: 'License',
  temporal: 'Temporal',
  tags: 'Tags',
};
