name: Tests
on: [pull_request, workflow_dispatch]
env:
  CODE_COVERAGE_THRESHOLD_REQUIRED: 33
jobs:
  lint-python:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install requirements
        run: pip install flake8 pycodestyle pytest pytest-ckan pytest-cov
      - name: Run flake8
        run: flake8 . --count --max-line-length=127 --statistics --exclude ckan

  lint-js:
    name: JS Lint and Build Metadata App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          yarn
          CI=false yarn build
      - name: Run eslint
        run: yarn lint:js

  test-js:
    needs: lint-js
    name: Node Tests for Metadata-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          yarn
          CI=false yarn build
      - name: Run node tests
        run: yarn test:metadata-app

  test:
    needs: lint-python
    strategy:
      matrix:
        ckan-version: [2.9]
      fail-fast: false

    name: Pytests for CKAN ${{ matrix.ckan-version }}
    runs-on: ubuntu-latest
    container:
      image: openknowledge/ckan-dev:${{ matrix.ckan-version }}
      volumes:
        - ${{ github.workspace }}:/app
    services:
      solr:
        image: datagov/catalog.data.gov.solr:latest
      db:
        image: ckan/ckan-postgres-dev:${{ matrix.ckan-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 10
      redis:
          image: redis:alpine
    env:
      ENV_FILE: .env
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@db/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@db/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@db/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apk add swig npm
        pip install -r dev-requirements.txt
        pip install -r requirements.txt
        pip install -e .
        npm install --global yarn
        yarn install
    - name: Run tests
      run: |
        source $ENV_FILE
        ckan -c test.ini db init
        yarn build
        pytest --ckan-ini=test.ini --cov=ckanext.dcat_usmetadata --cov-fail-under=${CODE_COVERAGE_THRESHOLD_REQUIRED} --disable-warnings ckanext/dcat_usmetadata/tests

  cypress_29:
    name: Cypress Tests for CKAN 2.9
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-files: [
          'additional-metadata.spec.js',
          'organization.spec.js',
          'required-metadata.spec.js',
          'user-flow.spec.js',
          'edit-dataset.spec.js',
          'publishers.spec.js',
          'resource-upload.spec.js'
        ]
      fail-fast: false
    env:
      ENV_FILE: .env
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@db/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@db/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@db/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: cypress
        run: |
          source $ENV_FILE
          CKAN_VERSION=2.9 yarn install
          CKAN_VERSION=2.9 yarn build
          CKAN_VERSION=2.9 yarn dockerize
          CKAN_VERSION=2.9 docker-compose -f docker-compose.yml -f docker-compose.cypress.yml run cypress /bin/bash -c "npx wait-on http://ckan:5000/api/action/status_show && npx cypress install && yarn && NODE_ENV=test npx cypress run --spec ${{ matrix.test-files }}"
      - name: cypress-artifacs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-artifacts
          path: |
            ./cypress/screenshots/
            ./cypress/videos/
